Initialise options.js
Most code still raw. Moved from UI.js

Exception: reference to shipConsole instead of viewConsole

&

Include filter for case where ship has all available properties

Filter excludes extend ship from options menu

(See corresponding commit in uicomponents.js for context)